services:
    web:
        # image: httpd
        build: 
            context: .
            dockerfile: web.dockerfile
        ports:
            - 80:80
        # volumes:
        #     - ./html:/var/www/html
    db:
        image: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: example
            MARIADB_DATABASE: wordpress
        volumes:
            - mariadbdata:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    mariadbdata: