services:
    web:
        # image: httpd
        build: 
            context: .
            dockerfile: web.dockerfile
        ports:
            - 80:80
        volumes:
            - ./html:/usr/local/apache2/htdocs